[versions]
ksp = "1.9.21-1.0.15"
kotlinJupyter = "0.11.0-358"
ktlint = "3.4.5"

# make sure to sync with :generator module
kotlin = "1.9.0"
kotlinpoet = "1.16.0"

dokka = "1.8.10"
libsPublisher = "0.0.60-dev-30"
# "Bootstrap" version of the dataframe, used in the build itself to generate @DataSchema APIs,
# dogfood Gradle / KSP plugins in tests and idea-examples modules
dataframe = "0.12.1"
korro = "0.1.5"
kover = "0.6.0-Beta"

commonsCsv = "1.8"
commonsCompress = "1.21"
klaxon = "5.5" # 5.6 requires Java 11
fuel = "2.3.1"
poi = "5.2.2"
mariadb = "3.1.4"
h2db = "2.2.224"
mysql = "8.0.33"
postgresql = "42.6.0"
sqlite = "3.42.0.1"
kotlinDatetime = "0.4.0"
openapi = "2.1.20"
kotlinLogging = "6.0.3"
sl4j = "2.0.12"

junit = "4.13.2"
junit-jupiter = "5.10.2"
junit-platform = "1.10.2"
kotestAsserions = "5.8.0"
jsoup = "1.14.3"
arrow = "11.0.0"
docProcessor = "0.3.2"
simpleGit = "2.0.3"
dependencyVersions = "0.51.0"
plugin-publish = "0.15.0"
shadow = "8.1.1"
android-gradle-api = "7.3.1"
ktor-server-netty = "2.3.8"
kotlin-compile-testing = "1.5.0"

[libraries]
ksp-gradle = { group = "com.google.devtools.ksp", name = "symbol-processing-gradle-plugin", version.ref = "ksp" }
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
jupyter-api = { group = "org.jetbrains.kotlinx", name = "kotlin-jupyter-kernel", version.ref = "kotlinJupyter" }

kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }

kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-scriptingJvm = { group = "org.jetbrains.kotlin", name = "kotlin-scripting-jvm", version.ref = "kotlin" }
commonsCsv = { group = "org.apache.commons", name = "commons-csv", version.ref = "commonsCsv" }
commonsCompress = { group = "org.apache.commons", name = "commons-compress", version.ref = "commonsCompress" }
klaxon = { group = "com.beust", name = "klaxon", version.ref = "klaxon" }
fuel = { group = "com.github.kittinunf.fuel", name = "fuel", version.ref = "fuel" }
poi = { group = "org.apache.poi", name = "poi", version.ref = "poi" }
mariadb = { group = "org.mariadb.jdbc", name = "mariadb-java-client", version.ref = "mariadb" }
h2db = { group = "com.h2database", name = "h2", version.ref = "h2db" }
mysql = { group = "mysql", name = "mysql-connector-java", version.ref = "mysql" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite" }

poi-ooxml = { group = "org.apache.poi", name = "poi-ooxml", version.ref = "poi" }
kotlin-datetimeJvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime-jvm", version.ref = "kotlinDatetime" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit-jupiter" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform-commons = { group = "org.junit.platform", name = "junit-platform-commons", version.ref = "junit-platform" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform" }
junit-platform-runner = { group = "org.junit.platform", name = "junit-platform-runner", version.ref = "junit-platform" }
junit-platform-suite-api = { group = "org.junit.platform", name = "junit-platform-suite-api", version.ref = "junit-platform" }

kotestAssertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotestAsserions" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }

arrow-format = { group = "org.apache.arrow", name = "arrow-format", version.ref = "arrow" }
arrow-vector = { group = "org.apache.arrow", name = "arrow-vector", version.ref = "arrow" }
arrow-memory = { group = "org.apache.arrow", name = "arrow-memory-unsafe", version.ref = "arrow" }

kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
swagger = { group = "io.swagger.parser.v3", name = "swagger-parser", version.ref = "openapi" }

kotlinLogging = { group = "io.github.oshai", name = "kotlin-logging", version.ref = "kotlinLogging" }
sl4j = { group = "org.slf4j", name = "slf4j-simple", version.ref = "sl4j" }
android-gradle-api = { group = "com.android.tools.build", name = "gradle-api", version.ref = "android-gradle-api" }
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-api" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin" }
kotlin-gradle-plugin-api = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin-api" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor-server-netty" }
kotlin-compile-testing = { group = "com.github.tschuchortdev", name = "kotlin-compile-testing", version.ref = "kotlin-compile-testing" }
kotlin-compile-testing-ksp = { group = "com.github.tschuchortdev", name = "kotlin-compile-testing-ksp", version.ref = "kotlin-compile-testing" }
kotlin-compiler = { group = "org.jetbrains.kotlin", name = "kotlin-compiler", version.ref = "kotlin" }
kotlin-compiler-embeddable = { group = "org.jetbrains.kotlin", name = "kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-compiler-internal-test-framework = { group = "org.jetbrains.kotlin", name = "kotlin-compiler-internal-test-framework", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlin-script-runtime = { group = "org.jetbrains.kotlin", name = "kotlin-script-runtime", version.ref = "kotlin" }
kotlin-annotations-jvm = { group = "org.jetbrains.kotlin", name = "kotlin-annotations-jvm", version.ref = "kotlin" }

[plugins]
jupyter-api = { id = "org.jetbrains.kotlin.jupyter.api", version.ref = "kotlinJupyter" }

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
keywordGenerator = { id = "org.jetbrains.dataframe.generator", version = "1.0" }
publisher = { id = "org.jetbrains.kotlin.libs.publisher", version.ref = "libsPublisher" }
korro = { id = "io.github.devcrocod.korro", version.ref = "korro" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "ktlint" }
dataframe = { id = "org.jetbrains.kotlinx.dataframe", version.ref = "dataframe" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
docProcessor = { id = "nl.jolanrensen.docProcessor", version.ref = "docProcessor" }
simpleGit = { id = "xyz.ronella.simple-git", version.ref = "simpleGit" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
dependencyVersions = { id = "com.github.ben-manes.versions", version.ref = "dependencyVersions" }
plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "plugin-publish" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
